name: Build and Deploy (GHCR + Railway)

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ secrets.RAILWAY_TOKEN != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: |
          # Try npm package then fallback to official installer
          set -e
          if ! npm i -g @railway/cli@latest; then
            curl -sL https://railway.app/install.sh | sh
          fi

      - name: Login to Railway (non-interactive)
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          # Try different login flags across CLI versions
          if railway login --apiKey "$RAILWAY_TOKEN" 2>/dev/null; then
            echo "Logged into Railway (apiKey)"
          elif railway login --token "$RAILWAY_TOKEN" 2>/dev/null; then
            echo "Logged into Railway (token)"
          else
            echo "Railway login failed - continue and attempt deploy (CLI may already be authenticated on runner)"
          fi

      - name: Deploy to Railway using pushed image
        env:
          IMAGE: ghcr.io/${{ github.repository }}:latest
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
          RAILWAY_SERVICE: ${{ secrets.RAILWAY_SERVICE }}
        run: |
          set -e
          echo "Deploying image: $IMAGE"
          if [ -n "$RAILWAY_PROJECT_ID" ] && [ -n "$RAILWAY_SERVICE" ]; then
            # Prefer explicit project/service deploy
            railway up --project "$RAILWAY_PROJECT_ID" --service "$RAILWAY_SERVICE" --image "$IMAGE" --detach || \
            railway deploy --project "$RAILWAY_PROJECT_ID" --service "$RAILWAY_SERVICE" --image "$IMAGE"
          else
            # Let Railway determine project/service (may create/link)
            railway up --image "$IMAGE" --detach || \
            railway deploy --image "$IMAGE" || \
            (echo "Railway deploy failed — check RAILWAY_TOKEN and CLI flags" && exit 1)
          fi
