name: Deploy to Railway

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node (for Railway CLI)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          set -e
          # Login using the token and deploy. The CLI will use the repo to detect the project.
          railway login --apiKey "$RAILWAY_TOKEN"
          # If you want non-interactive behavior, use 'railway up --detach' to deploy in background.
          railway up --detach
